<?php
/**
 * Body2
 *
 * PHP version 5
 *
 * @category Class
 * @package  VoximplantKit
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant Kit API Documentation
 *
 * <h1>Basic description</h1> <p>HTTP API is available via the <u>https://kitapi-{{region}}.voximplant.com/api/v3/<b>{method}</b></u> endpoint. To use the methods marked with the LOCK symbol, you need to create an api token on api tokens page. Pass this token as access token to each HTTP API call.</p> <h1>Authentication</h1> <p>This API uses Custom Query Parameter for its authentication.</p> <p>The parameters that are needed to be sent for this type of authentication are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VoximplantKit\Model;

use \ArrayAccess;
use VoximplantKit\ObjectSerializer;

/**
 * Body2 Class Doc Comment
 *
 * @category Class
 * @package  VoximplantKit
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Body2 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'body_2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'datetime_start' => 'string',
        'datetime_end' => 'string',
        'call_direction' => 'string',
        'scenario_ids' => 'string',
        'campaign_ids' => 'string',
        'phone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'datetime_start' => null,
        'datetime_end' => null,
        'call_direction' => null,
        'scenario_ids' => null,
        'campaign_ids' => null,
        'phone' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'datetime_start' => 'datetime_start',
        'datetime_end' => 'datetime_end',
        'call_direction' => 'call_direction',
        'scenario_ids' => 'scenario_ids',
        'campaign_ids' => 'campaign_ids',
        'phone' => 'phone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'datetime_start' => 'setDatetimeStart',
        'datetime_end' => 'setDatetimeEnd',
        'call_direction' => 'setCallDirection',
        'scenario_ids' => 'setScenarioIds',
        'campaign_ids' => 'setCampaignIds',
        'phone' => 'setPhone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'datetime_start' => 'getDatetimeStart',
        'datetime_end' => 'getDatetimeEnd',
        'call_direction' => 'getCallDirection',
        'scenario_ids' => 'getScenarioIds',
        'campaign_ids' => 'getCampaignIds',
        'phone' => 'getPhone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['datetime_start'] = isset($data['datetime_start']) ? $data['datetime_start'] : null;
        $this->container['datetime_end'] = isset($data['datetime_end']) ? $data['datetime_end'] : null;
        $this->container['call_direction'] = isset($data['call_direction']) ? $data['call_direction'] : null;
        $this->container['scenario_ids'] = isset($data['scenario_ids']) ? $data['scenario_ids'] : null;
        $this->container['campaign_ids'] = isset($data['campaign_ids']) ? $data['campaign_ids'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets datetime_start
     *
     * @return string
     */
    public function getDatetimeStart()
    {
        return $this->container['datetime_start'];
    }

    /**
     * Sets datetime_start
     *
     * @param string $datetime_start Start date. The format is 24-h ‘YYYY-MM-DD HH:mm:ss’ in UTC
     *
     * @return $this
     */
    public function setDatetimeStart($datetime_start)
    {
        $this->container['datetime_start'] = $datetime_start;

        return $this;
    }

    /**
     * Gets datetime_end
     *
     * @return string
     */
    public function getDatetimeEnd()
    {
        return $this->container['datetime_end'];
    }

    /**
     * Sets datetime_end
     *
     * @param string $datetime_end End date. The format is 24-h ‘YYYY-MM-DD HH:mm:ss’ in UTC
     *
     * @return $this
     */
    public function setDatetimeEnd($datetime_end)
    {
        $this->container['datetime_end'] = $datetime_end;

        return $this;
    }

    /**
     * Gets call_direction
     *
     * @return string
     */
    public function getCallDirection()
    {
        return $this->container['call_direction'];
    }

    /**
     * Sets call_direction
     *
     * @param string $call_direction Call direction (<b>example:</b> ‘call_direction=outgoing’ or ‘call_direction=incoming’ or ‘call_direction=all’)
     *
     * @return $this
     */
    public function setCallDirection($call_direction)
    {
        $this->container['call_direction'] = $call_direction;

        return $this;
    }

    /**
     * Gets scenario_ids
     *
     * @return string
     */
    public function getScenarioIds()
    {
        return $this->container['scenario_ids'];
    }

    /**
     * Sets scenario_ids
     *
     * @param string $scenario_ids Json integer array with scenarios IDs. The ID can be retrieved via the **searchScenarios** method. (<b>example:</b> scenario_ids=[1,2,3,...,9])
     *
     * @return $this
     */
    public function setScenarioIds($scenario_ids)
    {
        $this->container['scenario_ids'] = $scenario_ids;

        return $this;
    }

    /**
     * Gets campaign_ids
     *
     * @return string
     */
    public function getCampaignIds()
    {
        return $this->container['campaign_ids'];
    }

    /**
     * Sets campaign_ids
     *
     * @param string $campaign_ids Json integer array with campaign IDs. The ID can be retrieved via the **searchCampaigns** method. (<b>example:</b> campaign_ids=[1,2,3,...,9])
     *
     * @return $this
     */
    public function setCampaignIds($campaign_ids)
    {
        $this->container['campaign_ids'] = $campaign_ids;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone Phone number to filter. The response will include calls to the specified number only. The minimum number of digits is 3. (<b>example:</b> phone=15417543010)
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


