<?php
/**
 * MessagingOutgoingChatCloseEventTypeEventData
 *
 * PHP version 5
 *
 * @category Class
 * @package  VoximplantKit
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant Kit API Documentation
 *
 * <h1>Basic description</h1> <p>HTTP API is available via the <u>https://kitapi-{{region}}.voximplant.com/api/v3/<b>{method}</b></u> endpoint. To use the methods marked with the LOCK symbol, you need to create an api token on api tokens page. Pass this token as access token to each HTTP API call.</p> <h1>Authentication</h1> <p>This API uses Custom Query Parameter for its authentication.</p> <p>The parameters that are needed to be sent for this type of authentication are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VoximplantKit\Model;

use \ArrayAccess;
use VoximplantKit\ObjectSerializer;

/**
 * MessagingOutgoingChatCloseEventTypeEventData Class Doc Comment
 *
 * @category Class
 * @package  VoximplantKit
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagingOutgoingChatCloseEventTypeEventData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MessagingOutgoingChatCloseEventType_event_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'close_reason' => 'string',
        'sender_type' => '\VoximplantKit\Model\MessagingOutgoingChatCloseEventSenderType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'close_reason' => null,
        'sender_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'close_reason' => 'close_reason',
        'sender_type' => 'sender_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'close_reason' => 'setCloseReason',
        'sender_type' => 'setSenderType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'close_reason' => 'getCloseReason',
        'sender_type' => 'getSenderType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CLOSE_REASON_AGENT = 'CLOSED_BY_AGENT';
    const CLOSE_REASON_BOT = 'CLOSED_BY_BOT';
    const CLOSE_REASON_CLIENT_TIMEOUT = 'CLOSED_BY_CLIENT_TIMEOUT';
    const CLOSE_REASON_UNKNOWN_REASON = 'CLOSED_BY_UNKNOWN_REASON';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCloseReasonAllowableValues()
    {
        return [
            self::CLOSE_REASON_AGENT,
            self::CLOSE_REASON_BOT,
            self::CLOSE_REASON_CLIENT_TIMEOUT,
            self::CLOSE_REASON_UNKNOWN_REASON
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['close_reason'] = isset($data['close_reason']) ? $data['close_reason'] : null;
        $this->container['sender_type'] = isset($data['sender_type']) ? $data['sender_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['close_reason'] === null) {
            $invalidProperties[] = "'close_reason' can't be null";
        }
        $allowedValues = $this->getCloseReasonAllowableValues();
        if (!is_null($this->container['close_reason']) && !in_array($this->container['close_reason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'close_reason', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets close_reason
     *
     * @return string
     */
    public function getCloseReason()
    {
        return $this->container['close_reason'];
    }

    /**
     * Sets close_reason
     *
     * @param string $close_reason Allowed only CLOSED_BY_AGENT, CLOSED_BY_BOT, CLOSED_BY_CLIENT_TIMEOUT, CLOSED_BY_UNKNOWN_REASON
     *
     * @return $this
     */
    public function setCloseReason($close_reason)
    {
        $allowedValues = $this->getCloseReasonAllowableValues();
        if (!in_array($close_reason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'close_reason', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['close_reason'] = $close_reason;

        return $this;
    }

    /**
     * Gets sender_type
     *
     * @return \VoximplantKit\Model\MessagingOutgoingChatCloseEventSenderType
     */
    public function getSenderType()
    {
        return $this->container['sender_type'];
    }

    /**
     * Sets sender_type
     *
     * @param \VoximplantKit\Model\MessagingOutgoingChatCloseEventSenderType $sender_type sender_type
     *
     * @return $this
     */
    public function setSenderType($sender_type)
    {
        $this->container['sender_type'] = $sender_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


