<?php
/**
 * CallsHistoryTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VoximplantKit
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Voximplant Kit API Documentation
 *
 * <h1>Basic description</h1> <p>HTTP API is available via the <u>https://kitapi-{{region}}.voximplant.com/api/v3/<b>{method}</b></u> endpoint. To use the methods marked with the LOCK symbol, you need to create an api token on api tokens page. Pass this token as access token to each HTTP API call.</p> <h1>Authentication</h1> <p>This API uses Custom Query Parameter for its authentication.</p> <p>The parameters that are needed to be sent for this type of authentication are as follows:</p> <ul>   <li><strong>access_token</strong></li>   <li><strong>domain</strong></li> </ul>
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoximplantKit;

/**
 * CallsHistoryTypeTest Class Doc Comment
 *
 * @category    Class
 * @description CallsHistoryType
 * @package     VoximplantKit
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallsHistoryTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CallsHistoryType"
     */
    public function testCallsHistoryType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "attempt_num"
     */
    public function testPropertyAttemptNum()
    {
    }

    /**
     * Test attribute "calllist_item_id"
     */
    public function testPropertyCalllistItemId()
    {
    }

    /**
     * Test attribute "domain_id"
     */
    public function testPropertyDomainId()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "scenario_id"
     */
    public function testPropertyScenarioId()
    {
    }

    /**
     * Test attribute "datetime_start"
     */
    public function testPropertyDatetimeStart()
    {
    }

    /**
     * Test attribute "phone_a"
     */
    public function testPropertyPhoneA()
    {
    }

    /**
     * Test attribute "phone_b"
     */
    public function testPropertyPhoneB()
    {
    }

    /**
     * Test attribute "is_incoming"
     */
    public function testPropertyIsIncoming()
    {
    }

    /**
     * Test attribute "call_result_code"
     */
    public function testPropertyCallResultCode()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "record_url"
     */
    public function testPropertyRecordUrl()
    {
    }

    /**
     * Test attribute "call_cost"
     */
    public function testPropertyCallCost()
    {
    }

    /**
     * Test attribute "call_data"
     */
    public function testPropertyCallData()
    {
    }

    /**
     * Test attribute "call_resources"
     */
    public function testPropertyCallResources()
    {
    }

    /**
     * Test attribute "call_calls"
     */
    public function testPropertyCallCalls()
    {
    }

    /**
     * Test attribute "call_records"
     */
    public function testPropertyCallRecords()
    {
    }

    /**
     * Test attribute "call_status"
     */
    public function testPropertyCallStatus()
    {
    }

    /**
     * Test attribute "recalc"
     */
    public function testPropertyRecalc()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "processing"
     */
    public function testPropertyProcessing()
    {
    }
}
